// This file is autogenerated by qmake. It contains a function that
// references all resources the plugin includes and the function is
// referenced by Qt_(MOC_)EXPORT_PLUGIN to ensure the inclusion in
// the statically linked plugin.
#include <QtCore/qglobal.h>
void qwindows_plugin_resource_init() 
{
    Q_INIT_RESOURCE(cursors);
    Q_INIT_RESOURCE(openglblacklists);
}
